def get_indian_food_recipe(recipe_name):
    # Replace this dictionary with a real recipe database or API call
    indian_food_recipes = {
        "biryani": "Biryani is a mixed rice dish with its origins among the Muslims of the Indian subcontinent.",
        "chicken curry": "Chicken curry is a popular dish made with chicken, onions, tomatoes, and various spices.",
        "naan": "Naan is a type of Indian bread, traditionally baked in a clay oven called a tandoor.",
        "palak paneer": "Palak paneer is a vegetarian dish made with spinach and paneer (Indian cottage cheese).",
        "dosa": "Dosa is a fermented crepe made from rice batter and black lentils. It's a popular breakfast dish in South India.",
        "samosa": "Samosa is a fried or baked pastry with a savory filling, such as spiced potatoes, peas, and sometimes meat.",
        "Butter Chicken (Murgh Makhani)": "Grilled chicken cooked in a rich tomato-based gravy with butter and cream.",
        "Chicken Tikka Masala": "Marinated chicken pieces cooked in a spicy and creamy tomato-based sauce.",
        "Palak Paneer": "Cottage cheese cubes cooked in a creamy spinach gravy.",
        "Chana Masala": "Chickpeas cooked in a tangy tomato and spice-based sauce.",
        "Aloo Gobi": "Potatoes and cauliflower sautéed with spices.",
        "Vegetable Biryani": "Fragrant rice cooked with mixed vegetables and aromatic spices.",
        "Dal Makhani": "Creamy black lentils and red kidney beans cooked with spices and cream.",
        "Tandoori Chicken": "Chicken marinated in yogurt and spices, grilled or roasted.",
        "Samosa": "Triangular pastries filled with spiced potatoes and peas, deep-fried.",
        "Naan": "Soft and fluffy Indian flatbread made with all-purpose flour and baked in a tandoor.",
        "Chicken Korma": "Chicken cooked in a rich and aromatic yogurt-based sauce.",
        "Bhindi Masala": "Okra cooked with onions, tomatoes, and spices.",
        "Rajma Masala": "Red kidney beans cooked in a spiced tomato gravy.",
        "Malai Kofta": "Deep-fried cottage cheese and vegetable dumplings served in a creamy sauce.",
        "Pani Puri": "Hollow puris filled with spicy and tangy water, tamarind chutney, and chickpeas.",
        "Dosa": "Thin, crispy fermented rice and lentil crepes served with chutneys and sambar.",
        "Idli": "Steamed rice and lentil cakes, often served with chutney and sambar.",
        "Vada": "Deep-fried lentil fritters, usually served with chutney and sambar.",
        "Paneer Tikka": "Grilled paneer cubes marinated in spices and yogurt.",
        "Pav Bhaji": "Spiced vegetable mash served with buttered bread rolls.",
        "Chicken Biryani": "Fragrant rice cooked with marinated chicken and aromatic spices.",
        "Mutton Biryani": "Similar to chicken biryani but made with tender mutton.",
        "Aloo Paratha": "Whole wheat flatbread stuffed with spiced mashed potatoes and cooked on a griddle.",
        "Prawn Curry": "Prawns cooked in a flavorful coconut or tomato-based gravy.",
        "Chicken Curry": "Classic Indian chicken curry with a blend of spices and flavors.",
        "Vegetable Pulao": "Fragrant rice cooked with mixed vegetables and spices.",
        "Chicken Chettinad": "Spicy and aromatic chicken curry from the Chettinad region of Tamil Nadu.",
        "Prawn Biryani": "Fragrant rice cooked with marinated prawns and spices.",
        "Rava Dosa": "Thin and crispy crepe made with semolina and rice flour.",
        "Keema Curry": "Minced meat (often lamb or chicken) cooked with spices and onions.",
        "Gajar Halwa": "Carrot pudding made with grated carrots, milk, sugar, and nuts.",
        "Rasgulla": "Spongy cottage cheese balls soaked in sugar syrup.",
        "Gulab Jamun": "Deep-fried milk-based dumplings soaked in sugar syrup.",
        "Chicken 65": "Spicy and crispy fried chicken bites, usually served as an appetizer.",
        "Tandoori Fish": "Fish marinated in spices and yogurt, then grilled or roasted in a tandoor.",
        "Chicken Saagwala": "Chicken cooked with spinach and aromatic spices.",
        "Aloo Tikki": "Potato patties made with spices and shallow-fried.",
        "Fish Curry": "Fish pieces cooked in a flavorful sauce, often with coconut milk.",
        "Baingan Bharta": "Smoky roasted eggplant mashed and cooked with spices.",
        "Dahi Puri": "Small, hollow puris filled with yogurt, chutneys, and chickpeas.",
        "Chole Bhature": "Spiced chickpea curry served with deep-fried bread (bhature).",
        "Kheer": "Creamy and aromatic rice pudding made with milk and sugar.",
        "Chicken Baida Roti": "Stuffed bread with spiced chicken and egg mixture.",
        "Chicken Vindaloo": "A spicy Goan curry made with vinegar, chilies, and spices.",
        "Hyderabadi Biryani": "Flavorful rice dish from Hyderabad, often made with mutton.",
        "Chicken Handi": "Creamy and delicious chicken curry cooked in a handi (clay pot).",
        "Mushroom Masala": "Mushrooms cooked in a spiced tomato-based gravy.",
        "Malabar Fish Curry": "Fish curry with coconut milk, popular in the Malabar region of Kerala.",
        "Chicken Keema Samosa": "Samosas filled with spiced minced chicken.",
        "Gobi Manchurian": "Deep-fried cauliflower florets coated in a spicy and tangy sauce, with Indo-Chinese influence."
        # Add more recipes as needed
        # ...
    }
    recipe = indian_food_recipes.get(recipe_name.lower())
    return recipe
