def get_medical_condition(topic):
    medical_conditions = {
        "diabetes": "Diabetes is a metabolic disorder characterized by high blood sugar levels resulting from the body's inability to produce or effectively use insulin.",
        "hypertension": "Hypertension is a medical condition in which the blood pressure in the arteries is consistently elevated, leading to increased strain on the heart and blood vessels.",
        "asthma": "Asthma is a chronic respiratory condition that causes inflammation and narrowing of the airways, leading to breathing difficulties and wheezing.",
        "arthritis": "Arthritis is a group of joint disorders causing inflammation and pain, which can result in reduced mobility and joint function.",
        "migraine": "Migraine is a neurological disorder characterized by severe headaches, often accompanied by nausea, vomiting, and sensitivity to light and sound.",
        "depression": "Depression is a mental health disorder characterized by persistent sadness, loss of interest, and feelings of hopelessness or worthlessness.",
        "anxiety": "Anxiety is a mental health condition marked by excessive worry, fear, and apprehension, often accompanied by physical symptoms like rapid heart rate and sweating.",
        "alzheimer's disease": "Alzheimer's disease is a progressive neurodegenerative disorder that affects memory, cognitive function, and behavior.",
        "cancer": "Cancer is a group of diseases characterized by abnormal cell growth and the potential to invade and spread to other parts of the body.",
        "osteoporosis": "Osteoporosis is a condition where bones become weak and brittle, increasing the risk of fractures.",
        "parkinson's disease": "Parkinson's disease is a neurodegenerative disorder that affects movement, balance, and coordination due to a decrease in dopamine-producing neurons.",
        "epilepsy": "Epilepsy is a neurological disorder characterized by recurrent seizures caused by abnormal brain activity.",
        "stroke": "A stroke occurs when the blood supply to a part of the brain is interrupted or reduced, leading to brain cell damage and neurological deficits.",
        "chronic obstructive pulmonary disease": "COPD is a progressive lung disease that causes difficulty breathing due to damaged airways and reduced airflow.",
        "cardiovascular disease": "Cardiovascular disease encompasses various conditions affecting the heart and blood vessels, including coronary artery disease, heart failure, and arrhythmias.",
        "autism spectrum disorder": "ASD is a developmental disorder characterized by challenges in social interaction, communication, and repetitive behaviors.",
        "attention deficit hyperactivity disorder": "ADHD is a neurodevelopmental disorder characterized by inattention, hyperactivity, and impulsivity.",
        "celiac disease": "Celiac disease is an autoimmune disorder in which the consumption of gluten triggers an immune response that damages the small intestine.",
        "gastroesophageal reflux disease": "GERD is a chronic digestive disorder where stomach acid flows back into the esophagus, causing irritation and heartburn.",
        "hiv/aids": "HIV (Human Immunodeficiency Virus) is a virus that attacks the immune system, leading to acquired immunodeficiency syndrome (AIDS).",
        "multiple sclerosis": "MS is an autoimmune disease that affects the central nervous system, causing communication problems between the brain and the rest of the body.",
        "endometriosis": "Endometriosis is a condition in which tissue similar to the lining of the uterus grows outside the uterus, causing pain and possible fertility issues.",
        "fibromyalgia": "Fibromyalgia is a chronic pain disorder characterized by widespread musculoskeletal pain, fatigue, and tender points.",
        "glaucoma": "Glaucoma is a group of eye conditions that cause damage to the optic nerve, often due to increased intraocular pressure.",
        "inflammatory bowel disease": "IBD includes Crohn's disease and ulcerative colitis, which are chronic inflammatory conditions affecting the digestive tract.",
        "ovarian cancer": "Ovarian cancer is a type of cancer that originates in the ovaries and can spread to other parts of the body.",
        "schizophrenia": "Schizophrenia is a severe mental disorder characterized by abnormal social behavior, delusions, hallucinations, and disorganized thinking.",
        "systemic lupus erythematosus": "SLE is an autoimmune disease that can affect various organs and tissues, leading to inflammation and a range of symptoms.",
        "type 1 diabetes": "Type 1 diabetes is an autoimmune disease in which the immune system attacks and destroys insulin-producing cells in the pancreas.",
        "type 2 diabetes": "Type 2 diabetes is a metabolic disorder characterized by insulin resistance and high blood sugar levels.",
        "chronic kidney disease": "CKD is a condition where the kidneys gradually lose their function over time, leading to kidney failure.",
        "hepatitis": "Hepatitis is inflammation of the liver, usually caused by viral infections (e.g., hepatitis A, B, C).",
        "rheumatoid arthritis": "Rheumatoid arthritis is an autoimmune disease that primarily affects the joints, causing inflammation and joint damage.",
        "chronic fatigue syndrome": "CFS is a complex disorder characterized by severe fatigue that does not improve with rest and is not explained by other medical conditions.",
        "bipolar disorder": "Bipolar disorder is a mental health condition characterized by extreme mood swings, including periods of mania and depression.",
        "post-traumatic stress disorder": "PTSD is a mental health condition that can develop after experiencing or witnessing a traumatic event.",
        "hemophilia": "Hemophilia is a genetic bleeding disorder in which the blood does not clot properly.",
        "obesity": "Obesity is a medical condition characterized by excessive body fat accumulation, which can have negative health effects.",
        "cystic fibrosis": "Cystic fibrosis is a genetic disorder that affects the respiratory and digestive systems, leading to thick mucus production and organ damage.",
        "pancreatitis": "Pancreatitis is inflammation of the pancreas, which can be acute or chronic and may cause abdominal pain and digestive problems."
  }
    return medical_conditions.get(topic.lower())

